# k8s/edr-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edr-server
  labels:
    app: edr-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edr-server
  template:
    metadata:
      labels:
        app: edr-server
    spec:
      containers:
      - name: edr-server
        image: your-registry/edr-server:latest
        ports:
        - containerPort: 8000
        - containerPort: 9090
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: edr-secrets
              key: database-url
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: edr-secrets
              key: redis-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: edr-service
spec:
  selector:
    app: edr-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: LoadBalancer